---
- name: Create the database
  mysql_db:
    name: "{{ rds_database }}"
    state: present

- name: Create the database user
  mysql_user:
    login_host: "{{ db_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    name: "{{ rds_username }}"
    password: "{{ rds_password }}"
    priv:  "{{ rds_database }}.*:ALL"
  become: true
