---
- name: Get repo
  git:
    repo: "{{ repo }}"
    dest: "{{ repo_directory }}"
    accept_hostkey: yes

- name: Install .env
  become: true
  template: src=env.j2 dest={{repo_directory}}/.env force=yes mode=755

- name: Install database.yml
  become: true
  template: src=database.j2 dest={{repo_directory}}/config/database.yml force=yes mode=755

- name: delete the site
  file: path="/etc/nginx/sites-enabled/{{ app_name }}"
    state='absent'
  when: (state == 'absent')
  become: true

- name: "configure nginx site {{ app_name }}"
  template: src=site.j2
    dest="/etc/nginx/sites-enabled/{{ app_name }}"
    owner=root
    group=root
    mode=0644
  become: yes
  when: (state != 'absent')
