---
- name: Check for mpapis gpg key
  shell: gpg --list-keys mpapis
  register: mpapis_gpg_key_exists
  ignore_errors: true
  changed_when: False

- name: receiving key
  become: yes
  become_user: root
  become_method: sudo
  shell: "curl -sSL https://rvm.io/mpapis.asc | gpg --import -"
  register: shell_result
  changed_when: "'unchanged: 1' not in shell_result.stderr"

- name: downloading RVM installer
  become: yes
  become_user: root
  become_method: sudo
  get_url:
    url: "{{rvm_url}}"
    dest: "{{rvm_temp_installer_path}}"
    mode: 0755
  changed_when: False

- name: installing RVM
  become: yes
  become_user: root
  become_method: sudo
  command: "{{rvm_temp_installer_path}} --path {{rvm_root}} stable"
  register: command_result
  changed_when: "'Upgrading' not in command_result.stdout"

- name: removing RVM installer
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{rvm_temp_installer_path}}"
    state: absent
  changed_when: False

- name: setting RVM autolibs on
  become: yes
  become_user: root
  become_method: sudo
  command: "{{rvm_root}}/bin/rvm autolibs 3"
  changed_when: False

- name: installing Ruby
  become: yes
  become_user: root
  become_method: sudo
  command: "{{rvm_root}}/bin/rvm install {{rvm_default_ruby_version}}"
  register: command_result
  changed_when: "'Already installed' not in command_result.stderr"

- name: setting default Ruby version
  become: yes
  become_user: root
  become_method: sudo
  shell: "source {{rvm_init_script}} && rvm use {{rvm_default_ruby_version}} --default executable=/bin/bash"
  register: rvm_select_ruby_version_root
  ignore_errors: true
  changed_when: false

- name: Create symlinks to ruby and gem
  become: yes
  become_user: root
  become_method: sudo
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
    force: true
  with_items:
    - { src: '{{rvm_root}}/rubies/{{rvm_default_ruby_version}}/bin/ruby', dest: '/usr/local/bin/ruby' }
    - { src: '{{rvm_root}}/rubies/{{rvm_default_ruby_version}}/bin/gem', dest: '/usr/local/bin/gem' }

- set_fact:
    ruby_installed: yes
