---
- name: Install common packages
  apt: state=latest pkg={{ item }} update_cache={{ global_apt_update_cache }} cache_valid_time={{ global_apt_cache_valid_time }}
  become: yes
  with_items:
  - build-essential
  - htop
  - vim

- authorized_key: user={{ sudo_user }} key=https://github.com/{{item}}.keys
  with_items:
    - geclos
  become: true
