- name: Create deployment directory
  become: true
  file: path={{deploy_directory}} owner={{deploy_user}} group={{deploy_user}} state=directory
- name: Make shared directories
  file: path={{deploy_directory}}/shared/{{item}} group={{deploy_user}} owner={{deploy_user}} state=directory
  become: true
  with_items:
    - tmp
    - log
    - public
    - bundle
    - bin
    - config

- name: Create the database
  mysql_db:
    name: "{{ rds_database }}"
    state: present

- name: Create the database user
  mysql_user:
    login_host: "{{ db_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    name: "{{ rds_username }}"
    host: "%"
    password: "{{ rds_password }}"
  become: true

- name: Install .env
  become: true
  template: src=env.j2 dest={{deploy_directory}}/shared/.env force=yes mode=755 owner={{deploy_user}}

- name: Install database.yml
  become: true
  template: src=database.j2 dest={{deploy_directory}}/shared/config/database.yml force=yes mode=755 owner={{deploy_user}}
