---
- name: 'Development'
  hosts: development
  roles:
    - common
    - deploy
    - rvm.ruby
    - nodejs
    - python-mysqldb
    - database

- name: 'Web servers'
  hosts: webservers
  roles:
    - common
    - flow_backend
    - flow_frontend

- name: 'Database servers'
  hosts: dbservers
  roles:
    - common
    - mysql
